export const GET_BEANS_FAILURE = "GET_BEANS_FAILURE";
export const GET_BEANS_SUCCESS = "GET_BEANS_SUCCESS";

export const GET_FACTS_SUCCESS = "GET_FACTS_SUCCESS";
export const GET_FACTS_FAILURE = "GET_FACTS_FAILURE";
